# Base configs
baseurl: "/horama"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

navigation:
  - title: "Home"
    url: /
  - title: "Astrophotography"
    url: "{{ site.baseurl }}/astrophotography/"
  - title: "Landscapes"
    url: /landscapes/
  - title: "Nature"
    url: /nature/

# UI configs
title: "Horama by David C"
subtitle: "The perception of time through my eyes!"
author: "David C"
header:
 title: "Photography"
 subtitle: "by David C"
footer:
 name: "Hey there, my name is David C"
 bio: "Throughout my life, I have faced a unique challenge with the perception of time: my insatiable desire to learn. This yearning has led me to explore a variety of experiences, each valuable in its own right. My constant pursuit of knowledge guides me on this ephemeral journey, and I am grateful for every lesson I have had the fortune to learn"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/davcastroruiz"
  instagram: "https://www.instagram.com/davcastroruiz"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/davcastroruiz"
  github: "https://www.github.com/davcastroruiz"
